name: Lint Code Base

# on: [push, pull_request]
on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          # DEFAULT_BRANCH: main
          DEFAULT_BRANCH: ${{ github.head_ref }}
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_YAML: true
          VALIDATE_BASH: true
          VALIDATE_MARKDOWN: true 
          FILTER_REGEX_EXCLUDE: .*test/.*
          SUPER_LINTER_EXCLUDE: "**/*.sh, **/*.txt"
          #DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}